server {
    listen 80;
    server_name bracket.ai1to1.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name bracket.ai1to1.com;
    ssl_certificate /etc/letsencrypt/live/ai1to1.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ai1to1.com/privkey.pem;

    client_max_body_size 25m;

    location / {
        proxy_pass http://localhost:8400;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
