// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from './client';
import { client } from './client.gen';
import type {
  ActivateNextStageTournamentsTournamentIdStagesActivatePostData,
  ActivateNextStageTournamentsTournamentIdStagesActivatePostErrors,
  ActivateNextStageTournamentsTournamentIdStagesActivatePostResponses,
  AddMyFavoriteMeFavoritesTournamentIdPostData,
  AddMyFavoriteMeFavoritesTournamentIdPostErrors,
  AddMyFavoriteMeFavoritesTournamentIdPostResponses,
  AddMyTrustedManagerMeTrustedManagersPostData,
  AddMyTrustedManagerMeTrustedManagersPostErrors,
  AddMyTrustedManagerMeTrustedManagersPostResponses,
  AddParticipantTournamentsTournamentIdParticipantsPostData,
  AddParticipantTournamentsTournamentIdParticipantsPostErrors,
  AddParticipantTournamentsTournamentIdParticipantsPostResponses,
  AddTournamentScorerTournamentsTournamentIdScorersPostData,
  AddTournamentScorerTournamentsTournamentIdScorersPostErrors,
  AddTournamentScorerTournamentsTournamentIdScorersPostResponses,
  ApproveAndSettleAdminSettlementsTournamentIdApproveAndSettlePostData,
  ApproveAndSettleAdminSettlementsTournamentIdApproveAndSettlePostErrors,
  ApproveAndSettleAdminSettlementsTournamentIdApproveAndSettlePostResponses,
  ChangeStatusTournamentsTournamentIdChangeStatusPostData,
  ChangeStatusTournamentsTournamentIdChangeStatusPostErrors,
  ChangeStatusTournamentsTournamentIdChangeStatusPostResponses,
  CreateCategoryRatingCategoriesPostData,
  CreateCategoryRatingCategoriesPostErrors,
  CreateCategoryRatingCategoriesPostResponses,
  CreateCourtTournamentsTournamentIdCourtsPostData,
  CreateCourtTournamentsTournamentIdCourtsPostErrors,
  CreateCourtTournamentsTournamentIdCourtsPostResponses,
  CreateEliminationFromSourcesEndpointTournamentsTournamentIdStageItemsEliminationFromSourcesPostData,
  CreateEliminationFromSourcesEndpointTournamentsTournamentIdStageItemsEliminationFromSourcesPostErrors,
  CreateEliminationFromSourcesEndpointTournamentsTournamentIdStageItemsEliminationFromSourcesPostResponses,
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostData,
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostErrors,
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponses,
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostData,
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostErrors,
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponses,
  CreateNewClubClubsPostData,
  CreateNewClubClubsPostErrors,
  CreateNewClubClubsPostResponses,
  CreateRankingTournamentsTournamentIdRankingsPostData,
  CreateRankingTournamentsTournamentIdRankingsPostErrors,
  CreateRankingTournamentsTournamentIdRankingsPostResponses,
  CreateRoundRobinGroupsEndpointTournamentsTournamentIdStageItemsRoundRobinGroupsPostData,
  CreateRoundRobinGroupsEndpointTournamentsTournamentIdStageItemsRoundRobinGroupsPostErrors,
  CreateRoundRobinGroupsEndpointTournamentsTournamentIdStageItemsRoundRobinGroupsPostResponses,
  CreateRoundTournamentsTournamentIdRoundsPostData,
  CreateRoundTournamentsTournamentIdRoundsPostErrors,
  CreateRoundTournamentsTournamentIdRoundsPostResponses,
  CreateSinglePlayerTournamentsTournamentIdPlayersPostData,
  CreateSinglePlayerTournamentsTournamentIdPlayersPostErrors,
  CreateSinglePlayerTournamentsTournamentIdPlayersPostResponses,
  CreateStageItemTournamentsTournamentIdStageItemsPostData,
  CreateStageItemTournamentsTournamentIdStageItemsPostErrors,
  CreateStageItemTournamentsTournamentIdStageItemsPostResponses,
  CreateStageTournamentsTournamentIdStagesPostData,
  CreateStageTournamentsTournamentIdStagesPostErrors,
  CreateStageTournamentsTournamentIdStagesPostResponses,
  CreateTeamTournamentsTournamentIdTeamsPostData,
  CreateTeamTournamentsTournamentIdTeamsPostErrors,
  CreateTeamTournamentsTournamentIdTeamsPostResponses,
  CreateTournamentTournamentsPostData,
  CreateTournamentTournamentsPostErrors,
  CreateTournamentTournamentsPostResponses,
  DeleteClubClubsClubIdDeleteData,
  DeleteClubClubsClubIdDeleteErrors,
  DeleteClubClubsClubIdDeleteResponses,
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteData,
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteErrors,
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponses,
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteData,
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteErrors,
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponses,
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteData,
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteErrors,
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponses,
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteData,
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteErrors,
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponses,
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteData,
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteErrors,
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponses,
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteData,
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteErrors,
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponses,
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteData,
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteErrors,
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponses,
  DeleteTournamentTournamentsTournamentIdDeleteData,
  DeleteTournamentTournamentsTournamentIdDeleteErrors,
  DeleteTournamentTournamentsTournamentIdDeleteResponses,
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetData,
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetErrors,
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponses,
  GetClubsClubsGetData,
  GetClubsClubsGetResponses,
  GetCourtsTournamentsTournamentIdCourtsGetData,
  GetCourtsTournamentsTournamentIdCourtsGetErrors,
  GetCourtsTournamentsTournamentIdCourtsGetResponses,
  GetMetricsMetricsGetData,
  GetMetricsMetricsGetResponses,
  GetMeUsersUserIdGetData,
  GetMeUsersUserIdGetErrors,
  GetMeUsersUserIdGetResponses,
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetData,
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetErrors,
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponses,
  GetPlayersTournamentsTournamentIdPlayersGetData,
  GetPlayersTournamentsTournamentIdPlayersGetErrors,
  GetPlayersTournamentsTournamentIdPlayersGetResponses,
  GetRankingsTournamentsTournamentIdRankingsGetData,
  GetRankingsTournamentsTournamentIdRankingsGetErrors,
  GetRankingsTournamentsTournamentIdRankingsGetResponses,
  GetShowcaseShowcaseGetData,
  GetShowcaseShowcaseGetResponses,
  GetStagesTournamentsTournamentIdStagesGetData,
  GetStagesTournamentsTournamentIdStagesGetErrors,
  GetStagesTournamentsTournamentIdStagesGetResponses,
  GetTeamsTournamentsTournamentIdTeamsGetData,
  GetTeamsTournamentsTournamentIdTeamsGetErrors,
  GetTeamsTournamentsTournamentIdTeamsGetResponses,
  GetTournamentsTournamentsGetData,
  GetTournamentsTournamentsGetErrors,
  GetTournamentsTournamentsGetResponses,
  GetTournamentTournamentsTournamentIdGetData,
  GetTournamentTournamentsTournamentIdGetErrors,
  GetTournamentTournamentsTournamentIdGetResponses,
  GetUserUsersMeGetData,
  GetUserUsersMeGetResponses,
  LeaderboardRatingCategoriesCategoryIdLeaderboardGetData,
  LeaderboardRatingCategoriesCategoryIdLeaderboardGetErrors,
  LeaderboardRatingCategoriesCategoryIdLeaderboardGetResponses,
  LeaveTournamentTournamentsTournamentIdLeavePostData,
  LeaveTournamentTournamentsTournamentIdLeavePostErrors,
  LeaveTournamentTournamentsTournamentIdLeavePostResponses,
  ListAddableParticipantsTournamentsTournamentIdAddableParticipantsGetData,
  ListAddableParticipantsTournamentsTournamentIdAddableParticipantsGetErrors,
  ListAddableParticipantsTournamentsTournamentIdAddableParticipantsGetResponses,
  ListFollowedTournamentsMeTournamentsGetData,
  ListFollowedTournamentsMeTournamentsGetResponses,
  ListJoinableTournamentsMeJoinableTournamentsGetData,
  ListJoinableTournamentsMeJoinableTournamentsGetResponses,
  ListRatingCategoriesRatingCategoriesGetData,
  ListRatingCategoriesRatingCategoriesGetResponses,
  ListScorersTournamentsTournamentIdScorersGetData,
  ListScorersTournamentsTournamentIdScorersGetErrors,
  ListScorersTournamentsTournamentIdScorersGetResponses,
  ListTrustedManagersMeTrustedManagersGetData,
  ListTrustedManagersMeTrustedManagersGetResponses,
  ListUsersUsersGetData,
  ListUsersUsersGetResponses,
  LoginForAccessTokenTokenPostData,
  LoginForAccessTokenTokenPostErrors,
  LoginForAccessTokenTokenPostResponses,
  MoveTeamTournamentsTournamentIdTeamsTeamIdMovePostData,
  MoveTeamTournamentsTournamentIdTeamsTeamIdMovePostErrors,
  MoveTeamTournamentsTournamentIdTeamsTeamIdMovePostResponses,
  MyJoinStatusTournamentsTournamentIdMyJoinStatusGetData,
  MyJoinStatusTournamentsTournamentIdMyJoinStatusGetErrors,
  MyJoinStatusTournamentsTournamentIdMyJoinStatusGetResponses,
  MyRatingEventsMeRatingsCategoryIdEventsGetData,
  MyRatingEventsMeRatingsCategoryIdEventsGetErrors,
  MyRatingEventsMeRatingsCategoryIdEventsGetResponses,
  MyRatingsMeRatingsGetData,
  MyRatingsMeRatingsGetResponses,
  PingPingGetData,
  PingPingGetResponses,
  PutUserPasswordUsersUserIdPasswordPutData,
  PutUserPasswordUsersUserIdPasswordPutErrors,
  PutUserPasswordUsersUserIdPasswordPutResponses,
  RegisterDemoUserUsersRegisterDemoPostData,
  RegisterDemoUserUsersRegisterDemoPostErrors,
  RegisterDemoUserUsersRegisterDemoPostResponses,
  RegisterUserUsersRegisterPostData,
  RegisterUserUsersRegisterPostErrors,
  RegisterUserUsersRegisterPostResponses,
  RemoveCategoryRatingCategoriesCategoryIdDeleteData,
  RemoveCategoryRatingCategoriesCategoryIdDeleteErrors,
  RemoveCategoryRatingCategoriesCategoryIdDeleteResponses,
  RemoveMyFavoriteMeFavoritesTournamentIdDeleteData,
  RemoveMyFavoriteMeFavoritesTournamentIdDeleteErrors,
  RemoveMyFavoriteMeFavoritesTournamentIdDeleteResponses,
  RemoveMyTrustedManagerMeTrustedManagersManagerIdDeleteData,
  RemoveMyTrustedManagerMeTrustedManagersManagerIdDeleteErrors,
  RemoveMyTrustedManagerMeTrustedManagersManagerIdDeleteResponses,
  RemoveTournamentScorerTournamentsTournamentIdScorersUserIdDeleteData,
  RemoveTournamentScorerTournamentsTournamentIdScorersUserIdDeleteErrors,
  RemoveTournamentScorerTournamentsTournamentIdScorersUserIdDeleteResponses,
  RequestToJoinTournamentsTournamentIdJoinRequestsPostData,
  RequestToJoinTournamentsTournamentIdJoinRequestsPostErrors,
  RequestToJoinTournamentsTournamentIdJoinRequestsPostResponses,
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostData,
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostErrors,
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponses,
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostData,
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostErrors,
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponses,
  SeedTeamRatingTournamentsTournamentIdTeamsTeamIdSeedRatingPutData,
  SeedTeamRatingTournamentsTournamentIdTeamsTeamIdSeedRatingPutErrors,
  SeedTeamRatingTournamentsTournamentIdTeamsTeamIdSeedRatingPutResponses,
  SetShowcaseRankingTournamentsTournamentIdShowcaseRankingPutData,
  SetShowcaseRankingTournamentsTournamentIdShowcaseRankingPutErrors,
  SetShowcaseRankingTournamentsTournamentIdShowcaseRankingPutResponses,
  SettlementRequestTournamentsTournamentIdSettlementRequestPostData,
  SettlementRequestTournamentsTournamentIdSettlementRequestPostErrors,
  SettlementRequestTournamentsTournamentIdSettlementRequestPostResponses,
  SettlementReviewsAdminSettlementReviewsGetData,
  SettlementReviewsAdminSettlementReviewsGetResponses,
  SettlementStatusTournamentsTournamentIdSettlementStatusGetData,
  SettlementStatusTournamentsTournamentIdSettlementStatusGetErrors,
  SettlementStatusTournamentsTournamentIdSettlementStatusGetResponses,
  SettleTournamentsTournamentIdSettlePostData,
  SettleTournamentsTournamentIdSettlePostErrors,
  SettleTournamentsTournamentIdSettlePostResponses,
  UpdateCategoryRatingCategoriesCategoryIdPutData,
  UpdateCategoryRatingCategoriesCategoryIdPutErrors,
  UpdateCategoryRatingCategoriesCategoryIdPutResponses,
  UpdateClubClubsClubIdPutData,
  UpdateClubClubsClubIdPutErrors,
  UpdateClubClubsClubIdPutResponses,
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutData,
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutErrors,
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponses,
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutData,
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutErrors,
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponses,
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutData,
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutErrors,
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponses,
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutData,
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutErrors,
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponses,
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutData,
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutErrors,
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponses,
  UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData,
  UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors,
  UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses,
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutData,
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutErrors,
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponses,
  UpdateStageTournamentsTournamentIdStagesStageIdPutData,
  UpdateStageTournamentsTournamentIdStagesStageIdPutErrors,
  UpdateStageTournamentsTournamentIdStagesStageIdPutResponses,
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutData,
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutErrors,
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponses,
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostData,
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostErrors,
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponses,
  UpdateTournamentByIdTournamentsTournamentIdPutData,
  UpdateTournamentByIdTournamentsTournamentIdPutErrors,
  UpdateTournamentByIdTournamentsTournamentIdPutResponses,
  UpdateUserDetailsUsersUserIdPutData,
  UpdateUserDetailsUsersUserIdPutErrors,
  UpdateUserDetailsUsersUserIdPutResponses,
  UploadLogoTournamentsTournamentIdLogoPostData,
  UploadLogoTournamentsTournamentIdLogoPostErrors,
  UploadLogoTournamentsTournamentIdLogoPostResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Settlement Reviews
 */
export const settlementReviewsAdminSettlementReviewsGet = <ThrowOnError extends boolean = false>(
  options?: Options<SettlementReviewsAdminSettlementReviewsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    SettlementReviewsAdminSettlementReviewsGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/settlement-reviews',
    ...options,
  });

/**
 * Approve And Settle
 *
 * One admin action: approve every PENDING seed of this tournament's participants
 * (applying any per-player adjustment) and settle — atomically. The adjusted seed
 * becomes the player's frozen entry rating, so the settlement reflects it.
 */
export const approveAndSettleAdminSettlementsTournamentIdApproveAndSettlePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApproveAndSettleAdminSettlementsTournamentIdApproveAndSettlePostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    ApproveAndSettleAdminSettlementsTournamentIdApproveAndSettlePostResponses,
    ApproveAndSettleAdminSettlementsTournamentIdApproveAndSettlePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/settlements/{tournament_id}/approve-and-settle',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Clubs
 */
export const getClubsClubsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetClubsClubsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetClubsClubsGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs',
    ...options,
  });

/**
 * Create New Club
 */
export const createNewClubClubsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateNewClubClubsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNewClubClubsPostResponses,
    CreateNewClubClubsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Club
 */
export const deleteClubClubsClubIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteClubClubsClubIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteClubClubsClubIdDeleteResponses,
    DeleteClubClubsClubIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs/{club_id}',
    ...options,
  });

/**
 * Update Club
 */
export const updateClubClubsClubIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateClubClubsClubIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateClubClubsClubIdPutResponses,
    UpdateClubClubsClubIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs/{club_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove My Favorite
 */
export const removeMyFavoriteMeFavoritesTournamentIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<RemoveMyFavoriteMeFavoritesTournamentIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    RemoveMyFavoriteMeFavoritesTournamentIdDeleteResponses,
    RemoveMyFavoriteMeFavoritesTournamentIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/favorites/{tournament_id}',
    ...options,
  });

/**
 * Add My Favorite
 */
export const addMyFavoriteMeFavoritesTournamentIdPost = <ThrowOnError extends boolean = false>(
  options: Options<AddMyFavoriteMeFavoritesTournamentIdPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AddMyFavoriteMeFavoritesTournamentIdPostResponses,
    AddMyFavoriteMeFavoritesTournamentIdPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/favorites/{tournament_id}',
    ...options,
  });

/**
 * List Joinable Tournaments
 *
 * Public individual tournaments the current user could join right now —
 * the 可以参赛的比赛 tab on the home page.
 */
export const listJoinableTournamentsMeJoinableTournamentsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListJoinableTournamentsMeJoinableTournamentsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListJoinableTournamentsMeJoinableTournamentsGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/joinable-tournaments',
    ...options,
  });

/**
 * My Ratings
 */
export const myRatingsMeRatingsGet = <ThrowOnError extends boolean = false>(
  options?: Options<MyRatingsMeRatingsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<MyRatingsMeRatingsGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/ratings',
    ...options,
  });

/**
 * My Rating Events
 */
export const myRatingEventsMeRatingsCategoryIdEventsGet = <ThrowOnError extends boolean = false>(
  options: Options<MyRatingEventsMeRatingsCategoryIdEventsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    MyRatingEventsMeRatingsCategoryIdEventsGetResponses,
    MyRatingEventsMeRatingsCategoryIdEventsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/ratings/{category_id}/events',
    ...options,
  });

/**
 * List Followed Tournaments
 *
 * Tournaments the user follows (favorited or participates in).
 */
export const listFollowedTournamentsMeTournamentsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListFollowedTournamentsMeTournamentsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListFollowedTournamentsMeTournamentsGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/tournaments',
    ...options,
  });

/**
 * List Trusted Managers
 */
export const listTrustedManagersMeTrustedManagersGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListTrustedManagersMeTrustedManagersGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListTrustedManagersMeTrustedManagersGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/trusted-managers',
    ...options,
  });

/**
 * Add My Trusted Manager
 */
export const addMyTrustedManagerMeTrustedManagersPost = <ThrowOnError extends boolean = false>(
  options: Options<AddMyTrustedManagerMeTrustedManagersPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AddMyTrustedManagerMeTrustedManagersPostResponses,
    AddMyTrustedManagerMeTrustedManagersPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/trusted-managers',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove My Trusted Manager
 */
export const removeMyTrustedManagerMeTrustedManagersManagerIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RemoveMyTrustedManagerMeTrustedManagersManagerIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    RemoveMyTrustedManagerMeTrustedManagersManagerIdDeleteResponses,
    RemoveMyTrustedManagerMeTrustedManagersManagerIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/trusted-managers/{manager_id}',
    ...options,
  });

/**
 * Get Metrics
 */
export const getMetricsMetricsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMetricsMetricsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetMetricsMetricsGetResponses, unknown, ThrowOnError>({
    responseType: 'text',
    url: '/metrics',
    ...options,
  });

/**
 * Healthcheck ping
 */
export const pingPingGet = <ThrowOnError extends boolean = false>(
  options?: Options<PingPingGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<PingPingGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/ping',
    ...options,
  });

/**
 * List Rating Categories
 */
export const listRatingCategoriesRatingCategoriesGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListRatingCategoriesRatingCategoriesGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListRatingCategoriesRatingCategoriesGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rating-categories',
    ...options,
  });

/**
 * Create Category
 */
export const createCategoryRatingCategoriesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateCategoryRatingCategoriesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCategoryRatingCategoriesPostResponses,
    CreateCategoryRatingCategoriesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rating-categories',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove Category
 */
export const removeCategoryRatingCategoriesCategoryIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RemoveCategoryRatingCategoriesCategoryIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    RemoveCategoryRatingCategoriesCategoryIdDeleteResponses,
    RemoveCategoryRatingCategoriesCategoryIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rating-categories/{category_id}',
    ...options,
  });

/**
 * Update Category
 */
export const updateCategoryRatingCategoriesCategoryIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCategoryRatingCategoriesCategoryIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateCategoryRatingCategoriesCategoryIdPutResponses,
    UpdateCategoryRatingCategoriesCategoryIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rating-categories/{category_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Leaderboard
 */
export const leaderboardRatingCategoriesCategoryIdLeaderboardGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<LeaderboardRatingCategoriesCategoryIdLeaderboardGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    LeaderboardRatingCategoriesCategoryIdLeaderboardGetResponses,
    LeaderboardRatingCategoriesCategoryIdLeaderboardGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/rating-categories/{category_id}/leaderboard',
    ...options,
  });

/**
 * Get Showcase
 *
 * The Ra drop-in series: every public tournament of the series with its placement.
 *
 * Public on purpose — the page it feeds is meant to be shared with people who have no
 * account.
 */
export const getShowcaseShowcaseGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetShowcaseShowcaseGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetShowcaseShowcaseGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/showcase',
    ...options,
  });

/**
 * Login For Access Token
 */
export const loginForAccessTokenTokenPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginForAccessTokenTokenPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    LoginForAccessTokenTokenPostResponses,
    LoginForAccessTokenTokenPostErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/token',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  });

/**
 * Get Tournaments
 */
export const getTournamentsTournamentsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTournamentsTournamentsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetTournamentsTournamentsGetResponses,
    GetTournamentsTournamentsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments',
    ...options,
  });

/**
 * Create Tournament
 */
export const createTournamentTournamentsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTournamentTournamentsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateTournamentTournamentsPostResponses,
    CreateTournamentTournamentsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Tournament
 */
export const deleteTournamentTournamentsTournamentIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTournamentTournamentsTournamentIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteTournamentTournamentsTournamentIdDeleteResponses,
    DeleteTournamentTournamentsTournamentIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}',
    ...options,
  });

/**
 * Get Tournament
 */
export const getTournamentTournamentsTournamentIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTournamentTournamentsTournamentIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTournamentTournamentsTournamentIdGetResponses,
    GetTournamentTournamentsTournamentIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}',
    ...options,
  });

/**
 * Update Tournament By Id
 */
export const updateTournamentByIdTournamentsTournamentIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTournamentByIdTournamentsTournamentIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateTournamentByIdTournamentsTournamentIdPutResponses,
    UpdateTournamentByIdTournamentsTournamentIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Addable Participants
 */
export const listAddableParticipantsTournamentsTournamentIdAddableParticipantsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListAddableParticipantsTournamentsTournamentIdAddableParticipantsGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ListAddableParticipantsTournamentsTournamentIdAddableParticipantsGetResponses,
    ListAddableParticipantsTournamentsTournamentIdAddableParticipantsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/addable-participants',
    ...options,
  });

/**
 * Get Available Inputs
 */
export const getAvailableInputsTournamentsTournamentIdAvailableInputsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAvailableInputsTournamentsTournamentIdAvailableInputsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponses,
    GetAvailableInputsTournamentsTournamentIdAvailableInputsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/available_inputs',
    ...options,
  });

/**
 * Change Status
 *
 * Make a tournament archived or non-archived.
 */
export const changeStatusTournamentsTournamentIdChangeStatusPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChangeStatusTournamentsTournamentIdChangeStatusPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ChangeStatusTournamentsTournamentIdChangeStatusPostResponses,
    ChangeStatusTournamentsTournamentIdChangeStatusPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/change-status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Courts
 */
export const getCourtsTournamentsTournamentIdCourtsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCourtsTournamentsTournamentIdCourtsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCourtsTournamentsTournamentIdCourtsGetResponses,
    GetCourtsTournamentsTournamentIdCourtsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/courts',
    ...options,
  });

/**
 * Create Court
 */
export const createCourtTournamentsTournamentIdCourtsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateCourtTournamentsTournamentIdCourtsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCourtTournamentsTournamentIdCourtsPostResponses,
    CreateCourtTournamentsTournamentIdCourtsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/courts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Court
 */
export const deleteCourtTournamentsTournamentIdCourtsCourtIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponses,
    DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/courts/{court_id}',
    ...options,
  });

/**
 * Update Court By Id
 */
export const updateCourtByIdTournamentsTournamentIdCourtsCourtIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponses,
    UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/courts/{court_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Request To Join
 *
 * A logged-in user joins an individual tournament directly — no creator
 * approval, no rejection. Allowed only before play starts (no match generated).
 */
export const requestToJoinTournamentsTournamentIdJoinRequestsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RequestToJoinTournamentsTournamentIdJoinRequestsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RequestToJoinTournamentsTournamentIdJoinRequestsPostResponses,
    RequestToJoinTournamentsTournamentIdJoinRequestsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/join-requests',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Leave Tournament
 *
 * A participant withdraws themselves — removing their single-person team and
 * binding. Allowed only before play starts (no match generated) and never after
 * settlement.
 */
export const leaveTournamentTournamentsTournamentIdLeavePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<LeaveTournamentTournamentsTournamentIdLeavePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    LeaveTournamentTournamentsTournamentIdLeavePostResponses,
    LeaveTournamentTournamentsTournamentIdLeavePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/leave',
    ...options,
  });

/**
 * Upload Logo
 */
export const uploadLogoTournamentsTournamentIdLogoPost = <ThrowOnError extends boolean = false>(
  options: Options<UploadLogoTournamentsTournamentIdLogoPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UploadLogoTournamentsTournamentIdLogoPostResponses,
    UploadLogoTournamentsTournamentIdLogoPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/logo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Update Match By Id
 */
export const updateMatchByIdTournamentsTournamentIdMatchesMatchIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponses,
    UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Reschedule Match
 */
export const rescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponses,
    RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}/reschedule',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * My Join Status
 *
 * The current user's relationship to this tournament: whether they already
 * participate (a bound team), can manage it, and can record scores. Used to pick
 * the right 参赛 / 退出赛事 affordance.
 */
export const myJoinStatusTournamentsTournamentIdMyJoinStatusGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MyJoinStatusTournamentsTournamentIdMyJoinStatusGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    MyJoinStatusTournamentsTournamentIdMyJoinStatusGetResponses,
    MyJoinStatusTournamentsTournamentIdMyJoinStatusGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/my-join-status',
    ...options,
  });

/**
 * Get Next Stage Rankings
 *
 * Get the rankings for the stage items in this stage.
 */
export const getNextStageRankingsTournamentsTournamentIdNextStageRankingsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponses,
    GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/next_stage_rankings',
    ...options,
  });

/**
 * Add Participant
 */
export const addParticipantTournamentsTournamentIdParticipantsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AddParticipantTournamentsTournamentIdParticipantsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AddParticipantTournamentsTournamentIdParticipantsPostResponses,
    AddParticipantTournamentsTournamentIdParticipantsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/participants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Players
 */
export const getPlayersTournamentsTournamentIdPlayersGet = <ThrowOnError extends boolean = false>(
  options: Options<GetPlayersTournamentsTournamentIdPlayersGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetPlayersTournamentsTournamentIdPlayersGetResponses,
    GetPlayersTournamentsTournamentIdPlayersGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players',
    ...options,
  });

/**
 * Create Single Player
 */
export const createSinglePlayerTournamentsTournamentIdPlayersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSinglePlayerTournamentsTournamentIdPlayersPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateSinglePlayerTournamentsTournamentIdPlayersPostResponses,
    CreateSinglePlayerTournamentsTournamentIdPlayersPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Player
 */
export const deletePlayerTournamentsTournamentIdPlayersPlayerIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponses,
    DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players/{player_id}',
    ...options,
  });

/**
 * Update Player By Id
 */
export const updatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponses,
    UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players/{player_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Multiple Players
 */
export const createMultiplePlayersTournamentsTournamentIdPlayersMultiPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponses,
    CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players_multi',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Rankings
 */
export const getRankingsTournamentsTournamentIdRankingsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetRankingsTournamentsTournamentIdRankingsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetRankingsTournamentsTournamentIdRankingsGetResponses,
    GetRankingsTournamentsTournamentIdRankingsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/rankings',
    ...options,
  });

/**
 * Create Ranking
 */
export const createRankingTournamentsTournamentIdRankingsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateRankingTournamentsTournamentIdRankingsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateRankingTournamentsTournamentIdRankingsPostResponses,
    CreateRankingTournamentsTournamentIdRankingsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rankings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Ranking
 */
export const deleteRankingTournamentsTournamentIdRankingsRankingIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponses,
    DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rankings/{ranking_id}',
    ...options,
  });

/**
 * Update Ranking By Id
 */
export const updateRankingByIdTournamentsTournamentIdRankingsRankingIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponses,
    UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rankings/{ranking_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Round
 */
export const createRoundTournamentsTournamentIdRoundsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateRoundTournamentsTournamentIdRoundsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateRoundTournamentsTournamentIdRoundsPostResponses,
    CreateRoundTournamentsTournamentIdRoundsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rounds',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Round
 */
export const deleteRoundTournamentsTournamentIdRoundsRoundIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponses,
    DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rounds/{round_id}',
    ...options,
  });

/**
 * Update Round By Id
 */
export const updateRoundByIdTournamentsTournamentIdRoundsRoundIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponses,
    UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rounds/{round_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Schedule Matches
 */
export const scheduleMatchesTournamentsTournamentIdScheduleMatchesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponses,
    ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/schedule_matches',
    ...options,
  });

/**
 * List Scorers
 */
export const listScorersTournamentsTournamentIdScorersGet = <ThrowOnError extends boolean = false>(
  options: Options<ListScorersTournamentsTournamentIdScorersGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListScorersTournamentsTournamentIdScorersGetResponses,
    ListScorersTournamentsTournamentIdScorersGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/scorers',
    ...options,
  });

/**
 * Add Tournament Scorer
 */
export const addTournamentScorerTournamentsTournamentIdScorersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AddTournamentScorerTournamentsTournamentIdScorersPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AddTournamentScorerTournamentsTournamentIdScorersPostResponses,
    AddTournamentScorerTournamentsTournamentIdScorersPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/scorers',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove Tournament Scorer
 */
export const removeTournamentScorerTournamentsTournamentIdScorersUserIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RemoveTournamentScorerTournamentsTournamentIdScorersUserIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    RemoveTournamentScorerTournamentsTournamentIdScorersUserIdDeleteResponses,
    RemoveTournamentScorerTournamentsTournamentIdScorersUserIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/scorers/{user_id}',
    ...options,
  });

/**
 * Settle
 */
export const settleTournamentsTournamentIdSettlePost = <ThrowOnError extends boolean = false>(
  options: Options<SettleTournamentsTournamentIdSettlePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SettleTournamentsTournamentIdSettlePostResponses,
    SettleTournamentsTournamentIdSettlePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/settle',
    ...options,
  });

/**
 * Settlement Request
 */
export const settlementRequestTournamentsTournamentIdSettlementRequestPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SettlementRequestTournamentsTournamentIdSettlementRequestPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SettlementRequestTournamentsTournamentIdSettlementRequestPostResponses,
    SettlementRequestTournamentsTournamentIdSettlementRequestPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/settlement-request',
    ...options,
  });

/**
 * Settlement Status
 */
export const settlementStatusTournamentsTournamentIdSettlementStatusGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SettlementStatusTournamentsTournamentIdSettlementStatusGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    SettlementStatusTournamentsTournamentIdSettlementStatusGetResponses,
    SettlementStatusTournamentsTournamentIdSettlementStatusGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/settlement-status',
    ...options,
  });

/**
 * Set Showcase Ranking
 *
 * Correct the placement the showcase page shows for this tournament.
 *
 * Allowed on an archived tournament: the placement is a display correction, not a
 * result — the scores themselves stay frozen.
 */
export const setShowcaseRankingTournamentsTournamentIdShowcaseRankingPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SetShowcaseRankingTournamentsTournamentIdShowcaseRankingPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    SetShowcaseRankingTournamentsTournamentIdShowcaseRankingPutResponses,
    SetShowcaseRankingTournamentsTournamentIdShowcaseRankingPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/showcase-ranking',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Stage Item
 */
export const createStageItemTournamentsTournamentIdStageItemsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateStageItemTournamentsTournamentIdStageItemsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateStageItemTournamentsTournamentIdStageItemsPostResponses,
    CreateStageItemTournamentsTournamentIdStageItemsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Elimination From Sources Endpoint
 */
export const createEliminationFromSourcesEndpointTournamentsTournamentIdStageItemsEliminationFromSourcesPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      CreateEliminationFromSourcesEndpointTournamentsTournamentIdStageItemsEliminationFromSourcesPostData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).post<
      CreateEliminationFromSourcesEndpointTournamentsTournamentIdStageItemsEliminationFromSourcesPostResponses,
      CreateEliminationFromSourcesEndpointTournamentsTournamentIdStageItemsEliminationFromSourcesPostErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/tournaments/{tournament_id}/stage_items/elimination_from_sources',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });

/**
 * Create Round Robin Groups Endpoint
 */
export const createRoundRobinGroupsEndpointTournamentsTournamentIdStageItemsRoundRobinGroupsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateRoundRobinGroupsEndpointTournamentsTournamentIdStageItemsRoundRobinGroupsPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateRoundRobinGroupsEndpointTournamentsTournamentIdStageItemsRoundRobinGroupsPostResponses,
    CreateRoundRobinGroupsEndpointTournamentsTournamentIdStageItemsRoundRobinGroupsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items/round_robin_groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Stage Item
 */
export const deleteStageItemTournamentsTournamentIdStageItemsStageItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponses,
    DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}',
    ...options,
  });

/**
 * Update Stage Item
 */
export const updateStageItemTournamentsTournamentIdStageItemsStageItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponses,
    UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Stage Item Input
 */
export const updateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPut =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData,
      ThrowOnError
    >
  ) =>
    (options.client ?? client).put<
      UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses,
      UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}/inputs/{stage_item_input_id}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });

/**
 * Get Stages
 */
export const getStagesTournamentsTournamentIdStagesGet = <ThrowOnError extends boolean = false>(
  options: Options<GetStagesTournamentsTournamentIdStagesGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetStagesTournamentsTournamentIdStagesGetResponses,
    GetStagesTournamentsTournamentIdStagesGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/stages',
    ...options,
  });

/**
 * Create Stage
 */
export const createStageTournamentsTournamentIdStagesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateStageTournamentsTournamentIdStagesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateStageTournamentsTournamentIdStagesPostResponses,
    CreateStageTournamentsTournamentIdStagesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Activate Next Stage
 */
export const activateNextStageTournamentsTournamentIdStagesActivatePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ActivateNextStageTournamentsTournamentIdStagesActivatePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ActivateNextStageTournamentsTournamentIdStagesActivatePostResponses,
    ActivateNextStageTournamentsTournamentIdStagesActivatePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages/activate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Stage
 */
export const deleteStageTournamentsTournamentIdStagesStageIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteStageTournamentsTournamentIdStagesStageIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponses,
    DeleteStageTournamentsTournamentIdStagesStageIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages/{stage_id}',
    ...options,
  });

/**
 * Update Stage
 */
export const updateStageTournamentsTournamentIdStagesStageIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateStageTournamentsTournamentIdStagesStageIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateStageTournamentsTournamentIdStagesStageIdPutResponses,
    UpdateStageTournamentsTournamentIdStagesStageIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages/{stage_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Teams
 */
export const getTeamsTournamentsTournamentIdTeamsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTeamsTournamentsTournamentIdTeamsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTeamsTournamentsTournamentIdTeamsGetResponses,
    GetTeamsTournamentsTournamentIdTeamsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/teams',
    ...options,
  });

/**
 * Create Team
 */
export const createTeamTournamentsTournamentIdTeamsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTeamTournamentsTournamentIdTeamsPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateTeamTournamentsTournamentIdTeamsPostResponses,
    CreateTeamTournamentsTournamentIdTeamsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Team
 */
export const deleteTeamTournamentsTournamentIdTeamsTeamIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponses,
    DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}',
    ...options,
  });

/**
 * Update Team By Id
 */
export const updateTeamByIdTournamentsTournamentIdTeamsTeamIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponses,
    UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Team Logo
 */
export const updateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponses,
    UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}/logo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Move Team
 */
export const moveTeamTournamentsTournamentIdTeamsTeamIdMovePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MoveTeamTournamentsTournamentIdTeamsTeamIdMovePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    MoveTeamTournamentsTournamentIdTeamsTeamIdMovePostResponses,
    MoveTeamTournamentsTournamentIdTeamsTeamIdMovePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}/move',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Seed Team Rating
 */
export const seedTeamRatingTournamentsTournamentIdTeamsTeamIdSeedRatingPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SeedTeamRatingTournamentsTournamentIdTeamsTeamIdSeedRatingPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    SeedTeamRatingTournamentsTournamentIdTeamsTeamIdSeedRatingPutResponses,
    SeedTeamRatingTournamentsTournamentIdTeamsTeamIdSeedRatingPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}/seed-rating',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Multiple Teams
 */
export const createMultipleTeamsTournamentsTournamentIdTeamsMultiPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponses,
    CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams_multi',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Users
 *
 * Admin-only: all (non-demo) users with their ACTIVE per-category ratings,
 * without emails.
 */
export const listUsersUsersGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersUsersGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListUsersUsersGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users',
    ...options,
  });

/**
 * Get User
 */
export const getUserUsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserUsersMeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetUserUsersMeGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options,
  });

/**
 * Register User
 */
export const registerUserUsersRegisterPost = <ThrowOnError extends boolean = false>(
  options: Options<RegisterUserUsersRegisterPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RegisterUserUsersRegisterPostResponses,
    RegisterUserUsersRegisterPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/users/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Register Demo User
 */
export const registerDemoUserUsersRegisterDemoPost = <ThrowOnError extends boolean = false>(
  options: Options<RegisterDemoUserUsersRegisterDemoPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RegisterDemoUserUsersRegisterDemoPostResponses,
    RegisterDemoUserUsersRegisterDemoPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/users/register_demo',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Me
 */
export const getMeUsersUserIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetMeUsersUserIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetMeUsersUserIdGetResponses,
    GetMeUsersUserIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}',
    ...options,
  });

/**
 * Update User Details
 */
export const updateUserDetailsUsersUserIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserDetailsUsersUserIdPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateUserDetailsUsersUserIdPutResponses,
    UpdateUserDetailsUsersUserIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Put User Password
 */
export const putUserPasswordUsersUserIdPasswordPut = <ThrowOnError extends boolean = false>(
  options: Options<PutUserPasswordUsersUserIdPasswordPutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    PutUserPasswordUsersUserIdPasswordPutResponses,
    PutUserPasswordUsersUserIdPasswordPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
